version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '00:00'
    open-pull-requests-limit: 10
    groups:
      patches:
        update-types: ['patch']
    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      - dependency-name: 'cspell'
        update-types: ['version-update:semver-minor']
      - dependency-name: 'eslint*'
        update-types: ['version-update:semver-minor']
      - dependency-name: 'husky'
        update-types: ['version-update:semver-minor']
      - dependency-name: 'nodemon'
        update-types: ['version-update:semver-minor']
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '00:00'
    open-pull-requests-limit: 10
